#!/bin/bash
# Optional Desktop Applications Installer
# Description: Main installer for optional desktop applications
# Author: Generated by GitHub Copilot for Debian-WS

set -euo pipefail

# Source required dependencies
source "$(dirname "$0")/../../../lib/core/logging.sh"

# Script directory
SCRIPT_DIR="$(dirname "$0")"

# Install optional desktop applications
# Returns: 0 on success, 1 on failure
install_optional_desktop_apps() {
    log_info "Starting optional desktop applications installation..."

    echo "Welcome to Debian-WS Optional Desktop Applications Installer"
    echo "=========================================================="
    echo
    echo "Available categories:"
    echo "  1. Multimedia (VLC, GIMP, Audacity, OBS, Spotify, etc.)"
    echo "  2. Development (VSCode, VSCodium, Cursor, Zed, RubyMine, etc.)"
    echo "  3. Productivity (LibreOffice, Obsidian, Signal, 1Password, etc.)"
    echo "  4. Gaming & Entertainment (Steam, RetroArch, Minecraft, Discord)"
    echo "  5. All categories"
    echo "  6. Custom selection"
    echo

    read -p "Select category (1-6): " category_choice

    case "$category_choice" in
        1)
            log_info "Installing multimedia applications..."
            if ! "$SCRIPT_DIR/multimedia.sh"; then
                log_error "Failed to install multimedia applications"
                return 1
            fi
            ;;
        2)
            log_info "Installing development applications..."
            if ! "$SCRIPT_DIR/development.sh"; then
                log_error "Failed to install development applications"
                return 1
            fi
            ;;
        3)
            log_info "Installing productivity applications..."
            if ! "$SCRIPT_DIR/productivity.sh"; then
                log_error "Failed to install productivity applications"
                return 1
            fi
            ;;
        4)
            log_info "Installing gaming & entertainment applications..."
            if ! "$SCRIPT_DIR/gaming.sh"; then
                log_error "Failed to install gaming applications"
                return 1
            fi
            ;;
        5)
            log_info "Installing all categories..."
            local failed=0

            if ! "$SCRIPT_DIR/multimedia.sh"; then
                log_error "Failed to install multimedia applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/development.sh"; then
                log_error "Failed to install development applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/productivity.sh"; then
                log_error "Failed to install productivity applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/gaming.sh"; then
                log_error "Failed to install gaming applications"
                ((failed++))
            fi

            if [[ $failed -gt 0 ]]; then
                log_warning "$failed categories failed to install completely"
                return 1
            fi
            ;;
        6)
            log_info "Custom selection mode..."
            echo "You can run individual category scripts:"
            echo "  - Multimedia: $SCRIPT_DIR/multimedia.sh"
            echo "  - Development: $SCRIPT_DIR/development.sh"
            echo "  - Productivity: $SCRIPT_DIR/productivity.sh"
            echo "  - Gaming: $SCRIPT_DIR/gaming.sh"
            echo
            echo "Run them individually for custom selection within categories."
            return 0
            ;;
        *)
            log_error "Invalid selection: $category_choice"
            return 1
            ;;
    esac

    log_success "Optional desktop applications installation complete"
    return 0
}

# Execute main function if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_optional_desktop_apps
fi
