#!/bin/bash
# Optional Desktop Applications Installer
# Description: Main installer for optional desktop applications
# Author: Generated by GitHub Copilot for Debian-WS

set -euo pipefail

# Source required dependencies
source "$(dirname "$0")/../../../lib/core/logging.sh"
source "$(dirname "$0")/../../../lib/core/common.sh"

# Script directory
SCRIPT_DIR="$(dirname "$0")"

# Install optional desktop applications
# Returns: 0 on success, 1 on failure
install_optional_desktop_apps() {
    log_info "Starting optional desktop applications installation..."

    show_banner "Debian-WS Optional Desktop Applications"

    local categories=(
        "Multimedia (VLC, GIMP, Audacity, OBS, Spotify, etc.)"
        "Development (VSCode, VSCodium, Cursor, Zed, RubyMine, etc.)"
        "Productivity (LibreOffice, Obsidian, Signal, 1Password, etc.)"
        "Gaming & Entertainment (Steam, RetroArch, Minecraft, Discord)"
        "All categories"
        "Custom selection"
    )

    log_info "Available categories:"
    local category_choice=$(select_option "${categories[@]}")

    case "$category_choice" in
        "Multimedia"*)
            log_info "Installing multimedia applications..."
            if ! "$SCRIPT_DIR/multimedia.sh"; then
                log_error "Failed to install multimedia applications"
                return 1
            fi
            ;;
        "Development"*)
            log_info "Installing development applications..."
            if ! "$SCRIPT_DIR/development.sh"; then
                log_error "Failed to install development applications"
                return 1
            fi
            ;;
        "Productivity"*)
            log_info "Installing productivity applications..."
            if ! "$SCRIPT_DIR/productivity.sh"; then
                log_error "Failed to install productivity applications"
                return 1
            fi
            ;;
        "Gaming"*)
            log_info "Installing gaming & entertainment applications..."
            if ! "$SCRIPT_DIR/gaming.sh"; then
                log_error "Failed to install gaming applications"
                return 1
            fi
            ;;
        "All categories"*)
            log_info "Installing all categories..."
            local failed=0

            if ! "$SCRIPT_DIR/multimedia.sh"; then
                log_error "Failed to install multimedia applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/development.sh"; then
                log_error "Failed to install development applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/productivity.sh"; then
                log_error "Failed to install productivity applications"
                ((failed++))
            fi

            if ! "$SCRIPT_DIR/gaming.sh"; then
                log_error "Failed to install gaming applications"
                ((failed++))
            fi

            if [[ $failed -gt 0 ]]; then
                log_warning "$failed categories failed to install completely"
                return 1
            fi
            ;;
        "Custom selection"*)
            log_info "Custom selection mode..."
            echo "You can run individual category scripts:"
            echo "  - Multimedia: $SCRIPT_DIR/multimedia.sh"
            echo "  - Development: $SCRIPT_DIR/development.sh"
            echo "  - Productivity: $SCRIPT_DIR/productivity.sh"
            echo "  - Gaming: $SCRIPT_DIR/gaming.sh"
            echo
            echo "Run them individually for custom selection within categories."
            return 0
            ;;
        *)
            log_error "Invalid selection: $category_choice"
            return 1
            ;;
    esac

    log_success "Optional desktop applications installation complete"
    return 0
}

# Execute main function if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_optional_desktop_apps
fi
