#!/bin/bash
# System Required Applications Installer
# Description: Main installer for all required system applications
# Author: Generated by GitHub Copilot for Debian-WS

set -euo pipefail

# Source required dependencies
source "$(dirname "$0")/../../lib/core/logging.sh"

# Script directory
SCRIPT_DIR="$(dirname "$0")"

# Install all required system applications
# Returns: 0 on success, 1 on failure
install_system_required() {
    log_info "Starting system required applications installation..."

    # Check if running on supported system
    if ! command -v apt &> /dev/null; then
        log_error "APT package manager not found. This script requires Debian/Ubuntu."
        return 1
    fi

    # Check for sudo access
    if ! sudo -n true 2>/dev/null; then
        log_error "This script requires sudo access. Please run with sudo or ensure passwordless sudo is configured."
        return 1
    fi

    # Install terminal required applications
    log_info "Installing terminal required applications..."
    if ! "$SCRIPT_DIR/terminal-required.sh"; then
        log_error "Failed to install terminal required applications"
        return 1
    fi

    # Install desktop required applications
    log_info "Installing desktop required applications..."
    if ! "$SCRIPT_DIR/desktop-required.sh"; then
        log_error "Failed to install desktop required applications"
        return 1
    fi

    log_success "System required applications installation complete"
    return 0
}

# Execute main function if script is run directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    install_system_required
fi
